config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root "worklists#index"
  resources :worklists

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/list_review_r.rb
class ListReviewR < ApplicationRecord
	belongs_to :review
	belongs_to :worklist
end

app/models/review.rb
class Review < ApplicationRecord
	has_many :list_review_rs
	has_many :worklists, :through => :list_review_rs
end

app/models/school.rb
class School < ApplicationRecord
	has_many :worklists
end

app/models/worklist.rb
class Worklist < ApplicationRecord
	belongs_to :school
	validates_presence_of :title, :duedate, :description, :school_id
	has_many :list_review_rs
	has_many :reviews, :through => :list_review_rs
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/worklists_controller.rb
class WorklistsController < ApplicationController

	before_action :find_list, only: [:show, :edit, :update, :destroy]

	def index 
		@worklists=Worklist.page(params[:page]).per(5)  #預期使用者告訴我們他要第幾頁:page
	end

	def show
		@page_title=@worklist.title
	end

	def new
		@worklist=Worklist.new
	end

	def create
		@worklist=Worklist.new(work)
		if @worklist.save
			redirect_to worklists_url
			flash[:notice] = "event was successfully created"
		else
			render :new
		end
	end

	def edit

	end

	def update
		if @worklist.update(work)
			redirect_to worklist_url(@worklist)
		else
			render :edit
		end
	end

	def destroy
		@worklist.destroy
		redirect_to worklists_url
	end


	private

	def work
		params.require(:worklist).permit(:title, :duedate, :description, :school_id, :review_ids =>[])
	end

	def find_list		
		@worklist=Worklist.find(params[:id])
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/worklists_helper.rb
module WorklistsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title> <%=@page_title|| "To_Do_List" %></title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  	<div class="container">
      <h2 style="color: yellow"><%= flash[:notice] %></h2>
    	<%= yield %>
    </div>
  </body>
</html>

app/views/worklists/_form.html.erb
<% if @worklist.errors.present?%>
  <ul>
        <% @worklist.errors.each do |error, message|%>
          <li> <%= "#{error.capitalize}  #{message}" %></li>
        <% end %>
  </ul>
<% end%>




<%= form_for(@worklist) do |f| %>
  <div class="form-group">
    <%= f.label :school_id, "school"%>
    <%#= f.select :school_id, School.all.map{|x| [x.name, x.id]},:class=>"form-control"%>
    <%#= f.collection_select :school_id, School.all, :id, :name,:class=>"form-control", :include_blank=>"Please select"%>
    <% School.all.each do |s| %>
    <%= f.radio_button :school_id,s.id%><%= s.name%>

    <% end %>

  </div>

	<div class="form-group">
 		<%= f.label :title, "標題"%>
  	<%= f.text_field :title, :class=>"form-control"%>
 	</div>
 	<div class="form-group">
  	<%= f.label :duedate, "到期日"%>
  	<%= f.text_field :duedate, :class=>"form-control"%>
 	</div>
 	<div class="form-group">
  	<%= f.label :description, "敘述"%>
  	<%= f.text_field :description, :class=>"form-control"%>
  </div>
  
  <div class="form-group">
    
    <%= f.collection_check_boxes(:review_ids, Review.all, :id, :name) %>


  </div>

  	<%= f.submit "送出" ,:class=>"form-control"%>
<% end %>


<br><br><br>

<%= link_to 'Back_to_Home', worklists_path ,class:"btn btn-primary btn-xs"%>

app/views/worklists/edit.html.erb
<h1> Edit To-Do-List </h1>
<%= render :partial => "form"%>

app/views/worklists/index.html.erb
<h1> Vivian's To Do List </h1>



<ul>
 <% @worklists.each do |worklist| %>
  <li>
    <%= worklist.title %> </br>
    <%= worklist.duedate %> </br>
    <%= link_to 'Detail', worklist_path(worklist) ,class:"btn btn-info btn-xs"%>
    <%= link_to 'Edit', edit_worklist_path(worklist),class:"btn btn-primary btn-xs" %>
    <%= link_to 'Done&Delete', worklist_path(worklist), method: :delete, data:{ confirm: "Are you sure?"},class:"btn btn-danger btn-xs"%>
    </br></br>
  </li>
 <% end %>
</ul>


<%= link_to 'Add to-do-list?', new_worklist_path ,class:"btn btn-primary btn-xs"%>
<%= paginate @worklists %>

app/views/worklists/new.html.erb
<h1> Add New To-Do-List </h1>
<%= render :partial => "form" %>

app/views/worklists/show.html.erb
<h1><%= @worklist.title %></h1>

<h3> Due Date: <%= @worklist.duedate %> </h3>
<h3> School: <%= @worklist.school.name %></h3>

<hr> </br></br>
<%= @worklist.description%></br></br></br></br><hr>
<ul>Review: 
<% @worklist.reviews.each do |r| %>
	<li><%= r.name %></li>
<% end %>
</ul>
</br></br></br>

<%= link_to 'Back to homepage', worklists_path,class:"btn btn-primary btn-xs"%>